apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  # for tkgi in order to avoid "runAsRoot" issues.
  securityContext:
    runAsUser: 2000
    runAsGroup: 3000
  containers:
  - image: maciek01/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
