apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  labels:
    run: kubia
spec:
  replicas: 1
  selector:
    run: kubia
  template:
    metadata:
      labels:
        run: kubia
    spec:
      # for tkgi in order to avoid "runAsRoot" issues.
      securityContext:
        runAsUser: 2000
        runAsGroup: 3000
      containers:
      - name: kubia
        image: luksa/kubia:latest
        ports:
        - containerPort: 8080
          protocol: TCP
      
