apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      # for tkgi in order to avoid "runAsRoot" issues.
      securityContext:
        runAsUser: 2000
        runAsGroup: 3000
      containers:
      - name: kubia
        image: maciek01/kubia
        ports:
        - containerPort: 8080
